artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/lavaniarajeev001/datasets/blob/main/Salary_dataset.zip
  local_data_files: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion